name       : xorg-driver-video-matrox
version    : 2.0.0
release    : 8
source     :
    - https://www.x.org/archive/individual/driver/xf86-video-mga-2.0.0.tar.bz2 : 268946e1a13e9d80e4f724a0740df9e6e8c8bad37697fcbf456924e9fdbb5d79
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : Matrox Video Driver
description: |
    The Xorg MGA Driver package contains the X.Org Video Driver for Matrox video cards including Millennium G2xx, G4xx, G5xx, Millennium II and Mystique G200 chipsets.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
