name       : xorg-driver-video-matrox
version    : 1.6.5
release    : 4
source     :
    - https://www.x.org/archive/individual/driver/xf86-video-mga-1.6.5.tar.bz2 : b663cd8e6364f7c4e2637b9fcab9861d0e3971518c73b00d213f6545a1289422
license    : MIT
component  : xorg.driver
optimize   :
    - no-bind-now
    - no-symbolic
summary    : Matrox Video Driver
description: |
    The Xorg MGA Driver package contains the X.Org Video Driver for Matrox video cards including Millennium G2xx, G4xx, G5xx, Millennium II and Mystique G200 chipsets.
builddeps  :
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(xorg-macros)
    - pkgconfig(xorg-server)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
